// Code generated by protoc-gen-go. DO NOT EDIT.
// source: review.proto

package review

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type ProductInfo struct {
	ProductId            int32    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductInfo) Reset()         { *m = ProductInfo{} }
func (m *ProductInfo) String() string { return proto.CompactTextString(m) }
func (*ProductInfo) ProtoMessage()    {}
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_8626ff3b9064182a, []int{0}
}
func (m *ProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductInfo.Unmarshal(m, b)
}
func (m *ProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductInfo.Marshal(b, m, deterministic)
}
func (dst *ProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductInfo.Merge(dst, src)
}
func (m *ProductInfo) XXX_Size() int {
	return xxx_messageInfo_ProductInfo.Size(m)
}
func (m *ProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProductInfo proto.InternalMessageInfo

func (m *ProductInfo) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type Rate struct {
	Maximum              int32    `protobuf:"varint,1,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Current              int32    `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rate) Reset()         { *m = Rate{} }
func (m *Rate) String() string { return proto.CompactTextString(m) }
func (*Rate) ProtoMessage()    {}
func (*Rate) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_8626ff3b9064182a, []int{1}
}
func (m *Rate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rate.Unmarshal(m, b)
}
func (m *Rate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rate.Marshal(b, m, deterministic)
}
func (dst *Rate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rate.Merge(dst, src)
}
func (m *Rate) XXX_Size() int {
	return xxx_messageInfo_Rate.Size(m)
}
func (m *Rate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rate.DiscardUnknown(m)
}

var xxx_messageInfo_Rate proto.InternalMessageInfo

func (m *Rate) GetMaximum() int32 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *Rate) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

type ReviewMessage struct {
	ReviewId             int32    `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	ProductId            int32    `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ReviewerName         string   `protobuf:"bytes,3,opt,name=reviewer_name,json=reviewerName,proto3" json:"reviewer_name,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Rate                 *Rate    `protobuf:"bytes,5,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewMessage) Reset()         { *m = ReviewMessage{} }
func (m *ReviewMessage) String() string { return proto.CompactTextString(m) }
func (*ReviewMessage) ProtoMessage()    {}
func (*ReviewMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_8626ff3b9064182a, []int{2}
}
func (m *ReviewMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewMessage.Unmarshal(m, b)
}
func (m *ReviewMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewMessage.Marshal(b, m, deterministic)
}
func (dst *ReviewMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewMessage.Merge(dst, src)
}
func (m *ReviewMessage) XXX_Size() int {
	return xxx_messageInfo_ReviewMessage.Size(m)
}
func (m *ReviewMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewMessage proto.InternalMessageInfo

func (m *ReviewMessage) GetReviewId() int32 {
	if m != nil {
		return m.ReviewId
	}
	return 0
}

func (m *ReviewMessage) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *ReviewMessage) GetReviewerName() string {
	if m != nil {
		return m.ReviewerName
	}
	return ""
}

func (m *ReviewMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReviewMessage) GetRate() *Rate {
	if m != nil {
		return m.Rate
	}
	return nil
}

type ReviewMessages struct {
	ReviewMessages       []*ReviewMessage `protobuf:"bytes,1,rep,name=review_messages,json=reviewMessages,proto3" json:"review_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReviewMessages) Reset()         { *m = ReviewMessages{} }
func (m *ReviewMessages) String() string { return proto.CompactTextString(m) }
func (*ReviewMessages) ProtoMessage()    {}
func (*ReviewMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_8626ff3b9064182a, []int{3}
}
func (m *ReviewMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewMessages.Unmarshal(m, b)
}
func (m *ReviewMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewMessages.Marshal(b, m, deterministic)
}
func (dst *ReviewMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewMessages.Merge(dst, src)
}
func (m *ReviewMessages) XXX_Size() int {
	return xxx_messageInfo_ReviewMessages.Size(m)
}
func (m *ReviewMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewMessages.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewMessages proto.InternalMessageInfo

func (m *ReviewMessages) GetReviewMessages() []*ReviewMessage {
	if m != nil {
		return m.ReviewMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductInfo)(nil), "review.ProductInfo")
	proto.RegisterType((*Rate)(nil), "review.Rate")
	proto.RegisterType((*ReviewMessage)(nil), "review.ReviewMessage")
	proto.RegisterType((*ReviewMessages)(nil), "review.ReviewMessages")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReviewClient is the client API for Review service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReviewClient interface {
	// request an advertisement info
	GetMostHelpfulReviews(ctx context.Context, in *ProductInfo, opts ...grpc.CallOption) (*ReviewMessages, error)
}

type reviewClient struct {
	cc *grpc.ClientConn
}

func NewReviewClient(cc *grpc.ClientConn) ReviewClient {
	return &reviewClient{cc}
}

func (c *reviewClient) GetMostHelpfulReviews(ctx context.Context, in *ProductInfo, opts ...grpc.CallOption) (*ReviewMessages, error) {
	out := new(ReviewMessages)
	err := c.cc.Invoke(ctx, "/review.Review/GetMostHelpfulReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServer is the server API for Review service.
type ReviewServer interface {
	// request an advertisement info
	GetMostHelpfulReviews(context.Context, *ProductInfo) (*ReviewMessages, error)
}

func RegisterReviewServer(s *grpc.Server, srv ReviewServer) {
	s.RegisterService(&_Review_serviceDesc, srv)
}

func _Review_GetMostHelpfulReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).GetMostHelpfulReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/GetMostHelpfulReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).GetMostHelpfulReviews(ctx, req.(*ProductInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Review_serviceDesc = grpc.ServiceDesc{
	ServiceName: "review.Review",
	HandlerType: (*ReviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMostHelpfulReviews",
			Handler:    _Review_GetMostHelpfulReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}

func init() { proto.RegisterFile("review.proto", fileDescriptor_review_8626ff3b9064182a) }

var fileDescriptor_review_8626ff3b9064182a = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0x83, 0x30,
	0x18, 0xc6, 0xed, 0xc6, 0x50, 0x5e, 0xd8, 0x4c, 0x6a, 0x66, 0x1a, 0x8d, 0x09, 0xc1, 0x0b, 0x07,
	0xb3, 0x03, 0xde, 0x3c, 0x78, 0x54, 0x39, 0xcc, 0x90, 0x7e, 0x81, 0xa5, 0x42, 0x67, 0x48, 0x56,
	0x4a, 0xda, 0xa2, 0x7e, 0x28, 0x3f, 0xa4, 0x81, 0x16, 0xdd, 0x16, 0x8f, 0xcf, 0xf3, 0xbc, 0x7f,
	0x7e, 0xed, 0x0b, 0x91, 0xe2, 0x1f, 0x35, 0xff, 0x5c, 0xb5, 0x4a, 0x1a, 0x89, 0x7d, 0xab, 0x92,
	0x3b, 0x08, 0x0b, 0x25, 0xab, 0xae, 0x34, 0x79, 0xb3, 0x95, 0xf8, 0x06, 0xa0, 0xb5, 0x72, 0x53,
	0x57, 0x04, 0xc5, 0x28, 0x9d, 0xd1, 0xc0, 0x39, 0x79, 0x95, 0x3c, 0x80, 0x47, 0x99, 0xe1, 0x98,
	0xc0, 0xa9, 0x60, 0x5f, 0xb5, 0xe8, 0x84, 0xab, 0x19, 0x65, 0x9f, 0x94, 0x9d, 0x52, 0xbc, 0x31,
	0x64, 0x62, 0x13, 0x27, 0x93, 0x6f, 0x04, 0x73, 0x3a, 0x2c, 0x5d, 0x73, 0xad, 0xd9, 0x3b, 0xc7,
	0xd7, 0x10, 0x58, 0x8a, 0xbf, 0x5d, 0x67, 0xd6, 0xc8, 0xab, 0x23, 0x92, 0xc9, 0x11, 0x09, 0xbe,
	0x85, 0xb9, 0x2d, 0xe5, 0x6a, 0xd3, 0x30, 0xc1, 0xc9, 0x34, 0x46, 0x69, 0x40, 0xa3, 0xd1, 0x7c,
	0x65, 0x62, 0xc0, 0x2c, 0x65, 0x63, 0x7a, 0x18, 0x6f, 0x88, 0x47, 0x89, 0x63, 0xf0, 0x14, 0x33,
	0x9c, 0xcc, 0x62, 0x94, 0x86, 0x59, 0xb4, 0x72, 0x7f, 0xd3, 0x3f, 0x8e, 0x0e, 0x49, 0x52, 0xc0,
	0xe2, 0x80, 0x56, 0xe3, 0x47, 0x38, 0x77, 0xb8, 0xc2, 0x59, 0x04, 0xc5, 0xd3, 0x34, 0xcc, 0x96,
	0xbf, 0xed, 0xfb, 0x0d, 0x74, 0xa1, 0x0e, 0xfa, 0xb3, 0x02, 0x7c, 0x5b, 0x80, 0x9f, 0x60, 0xf9,
	0xcc, 0xcd, 0x5a, 0x6a, 0xf3, 0xc2, 0x77, 0xed, 0xb6, 0xdb, 0x59, 0x5f, 0xe3, 0x8b, 0x71, 0xd2,
	0xde, 0x4d, 0xae, 0x2e, 0xff, 0x1d, 0xaf, 0x93, 0x93, 0x37, 0x7f, 0xb8, 0xe5, 0xfd, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x56, 0x2e, 0x50, 0x0e, 0xdb, 0x01, 0x00, 0x00,
}
